### ISSUE TITLE
Openstack/Terraform: Add possibility to trigger TF_SCHEMA_PANIC_ON_ERROR=1

### ISSUE THREAD

**Issue by kayrus** [theopenlab/openlab#166]
The `TF_SCHEMA_PANIC_ON_ERROR` flag allows to catch invalid terraform schema assignments. It would be great if we can enable this environment variable as well as `TF_ACC=1`.

See the https://github.com/terraform-providers/terraform-provider-openstack/pull/601 as a reference.

**Comment by kiwik** [comment]
@kayrus thank you to report this, it looks make sense to add it, assign to @h00130372 to do it.

**Comment by jtopjian** [comment]
All,

I apologize, but please revert this.

This was not an approved change.

Thanks,
Joe

**Comment by kayrus** [comment]
I apologies, maybe my request was not clear. The aim was to control this environment variable, not to force it. However, since there are pending fixes for invalid schemas, I decided to wait for them to be merged.

**Comment by jtopjian** [comment]
@h00130372 

> Then how to control it?

I believe the intent of opening this issue was to see if it is possible to control. If it would require duplicating all jobs, then it's not worth the effort.

Having `TF_SCHEMA_PANIC_ON_ERROR` as a standard part of all tests is something that we will want to have done, but it is too early to do it right now. We will probably revisit this when we are sure `TF_SCHEMA_PANIC_ON_ERROR` won't cause tests to fail - possibly after Terraform v0.12 has been released since that might cause some new issues for us.

Again, I apologize for the confusion this caused.

**Comment by h00130372** [comment]
@jtopjian Sorry I am not quite clear, you mean this is new feature of Terraform and it's not stable, and maybe will cause some issue to use it now? And you plan to use it after Terraform v0.12?

**Comment by jtopjian** [comment]
@h00130372 I apologize.

`TF_SCHEMA_PANIC_ON_ERROR` is stable, but we need to fix things in `terraform-provider-openstack` or else it will cause all tests to fail.

Terraform v0.12 might cause further bugs on top of the issues we already have.

> And you plan to use it after Terraform v0.12?

Yes, I don't plan on adding this to our default test configurations until well after Terraform v0.12 is released and we can confirm that all issues are fixed.

It could be several months before we get to this point, so I am fine if you wanted to close this issue. I can open a new issue when the time is appropriate.

**Comment by h00130372** [comment]
@jtopjian Thanks for your clarification. Will close this issue first:)
