### ISSUE TITLE
Move gophercloud jobs to gophercloud repo

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab#17]

**Comment by yongfengdu** [comment]
Gophercloud should provide a script for the unittest and acceptance test, then we can just call that script in the CI playbooks.
1. The unittest part is OK, we just call  
./script/unittest -v 2>&1 | tee $TEST_RESULTS_TXT
2. The acceptance test needs more work. Ideally, we can just call 
./script/acceptancetest -v 2>&1 |tee $TEST_RESULTS_TXT
And gophercloud project should define what tests need to be run in the above acceptancetest script.

TO DISCUSS:
3. Since we support multiple versions of OpenStack, it is reasonable to provide version specific scripts to enable different accept tests, like acceptance-mitaka and acceptance-queens, to make sure the tests run being compatible with OpenStack API Versions(devstack).

**Comment by jtopjian** [comment]
> Would you provide a script/acceptencetest file to include all the desired tests ?

Yes, absolutely. 

To confirm: I'll merge this script into Gophercloud's `scripts` directory?

**Comment by mrhillsman** [comment]
Hi @yongfengdu 

We may want to consider this a bit more as I am still a bit concerned about requiring anything outside of gophercloud to run CI playbooks unless it is common jobs/roles/etc shareable across all projects that integrate the CI

I think we should try to come up with a modular approach to this. Have you had time to discuss with @animationzl @liu-sheng and/or @kiwik ?

**Comment by jtopjian** [comment]
I just realized that having OpenLab execute a script in Gophercloud might pose a security concern. There's technically nothing stopping someone from creating a PR which modifies the `scripts/acceptance.sh` file with malicious intent.

**Comment by yongfengdu** [comment]
@mrhillsman At a minimum, openlab still need a specified job config for gophercloud, right? Anyway, I'll discuss with them first to find a better way to handle this.

@jtopjian current CI job also need to run such tasks to execute go code(Not script) inside gophercloud, not sure if there is any difference? 
"go test -v -tags "fixtures acceptance" ./acceptance/openstack/identity/v3/"
Besides the security concern, I'll need to discuss further for a better solution with the team as Melvin mentioned.

**Comment by jtopjian** [comment]
> not sure if there is any difference?

You're right - there's not much of a difference.

**Comment by mrhillsman** [comment]
@yongfengdu all of the configuration and jobs can live in repo via zuul.yaml and playbooks, roles, etc directories/files. We only require updating our config so that when a payload is sent OpenLab says yes it will handle it; this is already the case.

@jtopjian there is something stopping that, the folks who have merge rights :) as a way to protect users of gophercloud, in terms of the CI system, PRs are run in an untrusted context so no privilege escalation exists.

**Comment by jtopjian** [comment]
> in terms of the CI system, PRs are run in an untrusted context so no privilege escalation exists.

right right - For a moment I thought that the hypothetical `scripts/acceptance.sh` script would run _outside_ of the sandboxed devstack environment. Momentary lapse on my part :)

**Comment by mrhillsman** [comment]
Hey @yongfengdu yes, sorry that I was not clear. Once we have everything in-repo for the gophercloud community at-large it should be easier to manage and make changes needed specifically for the community and also empower them to make things as modular as they need.
