### ISSUE TITLE
GitHub event notification to IRC channel #askopenlab

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab#252]
Let's make things better!

### Is your feature enhancement related to a problem? Please describe.
Not related to a specific problem.

### Describe the solution you'd like
When PRs, Issues, Push, or other events happen in GitHub - like a failing job status - an option to have a message sent to the #askopenlab IRC channel. Documentation providing implementation details and instructions for setting this up for projects OpenLab supports.

### Describe alternatives you've considered
N/A

### Additional context
OpenLab has a bot - openlab - running in #askopenlab IRC channel that receives events from two repos currently - openlab-zuul-jobs and openlab.

**Comment by kiwik** [comment]
Good idea, I think we can enable `new issue open` and `new pr open` in openlab, openlab-zuul-jobs and labkeeper projects to notify team to handle the new things, but I prefer to disable failing job status messages in IRC channel, because we have so many jobs, that will cause too many noise in IRC channel, and our new website will include the job testing result too.

@liu-sheng could you add the config for openlab IRC bot?

**Comment by kiwik** [comment]
The function have been enabled in OpenLab IRC channel #askopenlab on freenode.net
