### ISSUE TITLE
New Member

### ISSUE THREAD

**Issue by donnydavis** [theopenlab/openlab#484]
Welcome to OpenLab!

If you would like to join us, please leave your contact information below, we will invite you into OpenLab team later. As a member you will find out what's happening in OpenLab, what fellow open source community members are doing using OpenLab resources, also you can access OpenLab resources for your own testing.

### Full Name
Donny Davis
### Github account id
donnydavis
### Email
donny@fortnebula.com
### Company/Organization
open edge
### IRC nickname (Optional)
donnyd
### Job Title(optional)
this guy that does things

**Comment by bzhaoopenstack** [comment]
According to https://docs.openlabtesting.org/contributors/member-application , 
Seems people in group https://github.com/orgs/theopenlab/people?query=role%3Aowner has the priority to make you join. 
@wangxiyuan @liusheng Hi, guys, this seems need your help?

**Comment by donnydavis** [comment]
It would seem this is completely unmonitored, or the sign-up docs are not clear enough on what someone is supposed to do. Thanks anyways and good luck :)

**Comment by wangxiyuan** [comment]
@donnydavis Really sorry for no response.

Currently, it's meaningless to join the OpenLab Github team. Because there is nothing special or particular for the team member.

Without join the team, you still can do anything you want as before in OpenLab. i.e. you can ask to use OpenLab CI even you are not the member.

OpenLab is under re-design now. We'll reopen the join action once the refactor is done.

Sorry again.

**Comment by donnydavis** [comment]
Well I was going to try to participate as an infra provider for the CI, but I have already moved on.
