### ISSUE TITLE
Packer and Docker machine (07.23~08.10)

### ISSUE THREAD

**Issue by mrhillsman** [theopenlab/openlab#74]
https://github.com/hashicorp/packer/
https://www.packer.io/
https://docs.docker.com/machine/
https://github.com/docker/machine/

Test against
- OTC
- Orange
- Telefonica
- HuaweiCloud

Output
- Full functional tests and report
- Usage document

**Comment by kiwik** [comment]
All task have been finished. Close Issue.

**Comment by mrhillsman** [comment]
Packer rejected GitHub app installation/OpenLab integration - https://github.com/hashicorp/packer/issues/6874

**Comment by mrhillsman** [comment]
Packer rejected GitHub app installation/OpenLab integration - https://github.com/hashicorp/packer/issues/6874

**Comment by kiwik** [comment]
Because Packer rejected integration and docker machine is in maintain mode https://github.com/docker/machine/issues/4537 , we decide to run integration test against OpenLab forked projects https://github.com/theopenlab/packer and https://github.com/theopenlab/machine , and keep sync manually with upstream periodically
